language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-21
    - android-24
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository

script: ./gradlew